name: Apply Created Action
on: [push, pull_request]

jobs:
  Greet:
    runs-on: ubuntu-latest
    
    steps:          
    - name: Greet Someone
      id: hello
      uses: actions/prem-docker-action@v1
      with:
         who-to-greet: 'KALAIVANI'
          
    - name: get the output
      run: echo ${{ steps.hello.outputs.time }}
          
          
    
